name: Manual Publish PowerAzPlus Module

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3      

      # Publish the module
      - name: Publish module to PowerShell Gallery
        run: |
          "Value: ${{ github.workspace }}"
          $env:PSGalleryApiKey = "${{ secrets.POWERSHELLGALLERY_API_KEY }}"
          Publish-Module -Path ./PowerAzPlus -Repository PSGallery -NuGetApiKey $env:PSGalleryApiKey -Verbose
        shell: pwsh
