name: Pull Request Merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install PlatyPS
        shell: pwsh
        run: Install-Module -Name PlatyPS -Force -Scope CurrentUser

      - name: Generate XML Help
        shell: pwsh
        run: New-ExternalHelp -Path ".\docs" -OutputPath "." -Force

      - name: Commit and Push Help Updates
        shell: pwsh
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add PowerAzPlus-help.xml
          git commit -m "chore: update help documentation" || echo "No changes to help file"
          git push

      - name: Publish module to PowerShell Gallery
        shell: pwsh
        env:
          PSGalleryApiKey: ${{ secrets.POWERSHELLGALLERY_API_KEY }}
        run: Publish-Module -Path . -Repository PSGallery -NuGetApiKey $env:PSGalleryApiKey        
